version: '3.5'

volumes:
  postgres_data:
  rabbitmq-data:
 
services:  
    
  #Postgres server container
  postgres:
    image: postgres:latest
    restart: always
    network_mode: bridge
    environment: 
        - POSTGRES_USER=voteserv
        - POSTGRES_PASSWORD=voteserv@123
        - POSTGRES_DB=vote-service
    container_name: postgres-server
    expose:
      - 5432
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  #RabbitMq server container
  rabbitmq:
    
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: voteserv
      RABBITMQ_DEFAULT_PASS: voteserv@123
    container_name: rabbitmq-server
    network_mode: bridge
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
     
  #Vote service application container   
  vote-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: rogeriodcb/vote-service:latest
    network_mode: bridge
    container_name: vote-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_RABBITMQ_HOST=rabbitmq
    expose:
      - 8081
    ports:
      - 8081:8081
    depends_on:
      - postgres
      - rabbitmq
    links:
      - postgres
      - rabbitmq
    